// <auto-generated />
using System;
using API_DEVinCar_Graphql.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_DEVinCar_Graphql.Migrations
{
    [DbContext(typeof(DEVInCarContext))]
    partial class DEVInCarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_DEVinCar_Graphql.Data.Models.Usuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123456",
                            Username = "Yan"
                        },
                        new
                        {
                            Id = 2,
                            Password = "654321",
                            Username = "Fernando"
                        },
                        new
                        {
                            Id = 3,
                            Password = "qwerty",
                            Username = "Lucas"
                        });
                });

            modelBuilder.Entity("API_DEVinCar_Graphql.Data.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("int");

                    b.Property<string>("VeiculoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("API_DEVinCar_Graphql.Models.Camionete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CapacidadeCacamba")
                        .HasColumnType("int");

                    b.Property<Guid>("Chassi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portas")
                        .HasColumnType("int");

                    b.Property<double>("Potencia")
                        .HasColumnType("float");

                    b.Property<int>("TipoCombustivel")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Camionetes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadeCacamba = 844,
                            Chassi = new Guid("84ef5d8a-e9d0-4383-b3cd-aaf4664a82be"),
                            Cor = "Prata",
                            DataFabricacao = new DateTime(2021, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            Nome = "Strada",
                            Placa = "CAM-0397",
                            Portas = 2,
                            Potencia = 107.0,
                            TipoCombustivel = 0,
                            Valor = 109990.0
                        },
                        new
                        {
                            Id = 2,
                            CapacidadeCacamba = 1570,
                            Chassi = new Guid("a3dc3c2b-5a73-41c5-8a00-4125ce3e47e3"),
                            Cor = "Vermelho",
                            DataFabricacao = new DateTime(2020, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disponivel = false,
                            Nome = "Hilux",
                            Placa = "CAM-0397",
                            Portas = 4,
                            Potencia = 204.0,
                            TipoCombustivel = 1,
                            Valor = 260390.0
                        },
                        new
                        {
                            Id = 3,
                            CapacidadeCacamba = 580,
                            Chassi = new Guid("8be076ae-d989-4d60-9612-5791395ac969"),
                            Cor = "Azul",
                            DataFabricacao = new DateTime(2021, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            Nome = "Saveiro",
                            Placa = "CAM-0397",
                            Portas = 2,
                            Potencia = 71.0,
                            TipoCombustivel = 1,
                            Valor = 99000.0
                        });
                });

            modelBuilder.Entity("API_DEVinCar_Graphql.Models.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("Chassi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<bool>("Flex")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portas")
                        .HasColumnType("int");

                    b.Property<double>("Potencia")
                        .HasColumnType("float");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Carros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chassi = new Guid("bdacb84e-8a29-47db-a0fa-f7c6dd2c2db4"),
                            Cor = "Vermelho",
                            DataFabricacao = new DateTime(2022, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disponivel = false,
                            Flex = true,
                            Nome = "Kwid",
                            Placa = "ABC-1234",
                            Portas = 4,
                            Potencia = 71.0,
                            Valor = 59999.900000000001
                        },
                        new
                        {
                            Id = 2,
                            Chassi = new Guid("5fcceea7-8346-4927-8409-06a596433f4b"),
                            Cor = "Vermelho",
                            DataFabricacao = new DateTime(2013, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disponivel = false,
                            Flex = true,
                            Nome = "Uno",
                            Placa = "XYZ-6789",
                            Portas = 2,
                            Potencia = 65.0,
                            Valor = 24999.900000000001
                        },
                        new
                        {
                            Id = 3,
                            Chassi = new Guid("f8992d7a-82e8-4525-a835-9bade808d198"),
                            Cor = "Preto",
                            DataFabricacao = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            Flex = false,
                            Nome = "Ka",
                            Placa = "AAA-1111",
                            Portas = 4,
                            Potencia = 71.0,
                            Valor = 49999.900000000001
                        });
                });

            modelBuilder.Entity("API_DEVinCar_Graphql.Models.MotoTriciclo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("Chassi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Potencia")
                        .HasColumnType("float");

                    b.Property<int>("Rodas")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("MotoTriciclos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chassi = new Guid("287f00e6-ea6e-4f37-a9ea-0936f6d75d7d"),
                            Cor = "Azul",
                            DataFabricacao = new DateTime(2016, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            Nome = "Biz",
                            Placa = "ASD-4123",
                            Potencia = 8.3300000000000001,
                            Rodas = 2,
                            Valor = 8900.0
                        },
                        new
                        {
                            Id = 2,
                            Chassi = new Guid("f7dd0745-66f0-4e75-91f9-33b01c24d5a0"),
                            Cor = "Preto",
                            DataFabricacao = new DateTime(2018, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            Nome = "CG-160",
                            Placa = "FED-5193",
                            Potencia = 14.9,
                            Rodas = 2,
                            Valor = 10520.0
                        },
                        new
                        {
                            Id = 3,
                            Chassi = new Guid("97068bbc-fdee-4740-8ebe-ae56ef5dae63"),
                            Cor = "Preto",
                            DataFabricacao = new DateTime(2017, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disponivel = false,
                            Nome = "Spider",
                            Placa = "BSC-9297",
                            Potencia = 21.0,
                            Rodas = 3,
                            Valor = 16999.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
